AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AppSync Service Proxy Sample
Parameters:
  ProjectPrefix:
    Type: String
    Default: ""

Resources:
  #-------------------------------------------------------
  # AppSync
  #-------------------------------------------------------
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppSyncServiceRole.Arn
        ExcludeVerboseContent: false
        FieldLogLevel: ALL
      Name: !Sub ${ProjectPrefix}AppSync
      XrayEnabled: true
  GraphQLApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId

  #Schema
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DefinitionS3Location: schema.graphql

  #DataSource
  LambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: LambdaDataSource
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !Sub ${TargetLambda.Arn}

  #Resolver
  LambdaResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: invokeFunction
      DataSourceName: !GetAtt LambdaDataSource.Name
      Runtime:
        Name: "APPSYNC_JS"
        RuntimeVersion: "1.0.0"
      Code: |-
        import { util } from "@aws-appsync/utils";

        export function request(ctx) {
          const { source, args } = ctx;
          return {
            operation: "Invoke",
            payload: { field: ctx.info.fieldName, arguments: args, source },
          };
        }

        export const response = (ctx) => ctx.result;

  #-------------------------------------------------------
  # IAM
  #-------------------------------------------------------
  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
      Policies:
        - PolicyName: proxy-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - logs:*
                Resource: "*"
      Path: /
      RoleName: !Sub ${ProjectPrefix}AppSyncServiceRole

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      Path: /
      RoleName: !Sub ${ProjectPrefix}LambdaRole

  #-------------------------------------------------------
  #   CloudWatchLogs
  #-------------------------------------------------------
  GraphQLApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/appsync/apis/${GraphQLApi.ApiId}

  TargetLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${TargetLambda}

  #-------------------------------------------------------
  # Lambda
  #-------------------------------------------------------
  TargetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/target_lambda
      FunctionName: !Sub ${ProjectPrefix}TargetLambda
      Handler: target_lambda.lambda_handler
      MemorySize: 128
      Role: !Sub ${LambdaRole.Arn}
      Runtime: python3.12
      Timeout: 29
      Tracing: Active
      Environment:
        Variables:
          LOG_LEVEL: DEBUG
